(function(){
'use strict';
const SB=()=>window.barokahSupabase||null;
const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const money=v=>'Rp '+Number(v||0).toLocaleString('id-ID');
const date=v=>{if(!v)return '-';const p=String(v).split('-');return p.length===3?p[2]+'-'+p[1]+'-'+p[0]:String(v)};
let rows=[];let kind='piutang';let bound=false;let rendering=false;
async function user(){const sb=SB();if(!sb)return null;const r=await sb.auth.getUser();return r.data?.user||null}
async function load(){const sb=SB(),u=await user();if(!sb||!u)return[];const q=await sb.from('debts_receivables').select('id,kind,party_type,party_name,phone,reference_no,debt_date,total_amount,paid_amount,quantity,unit,note').eq('user_id',u.id).order('debt_date',{ascending:false});if(q.error)throw q.error;return q.data||[]}
function activeKind(){const p=document.querySelector('#page-debt');if(!p)return kind;const a=[...p.querySelectorAll('button')].find(b=>b.classList.contains('active')&&/Piutang Pelanggan|Utang Supplier/i.test(b.textContent||''));return a?(/Utang Supplier/i.test(a.textContent)?'utang':'piutang'):kind}
function css(){if(document.getElementById('debtHistory63Css'))return;const s=document.createElement('style');s.id='debtHistory63Css';s.textContent=`
.b63-history{margin-top:12px;min-width:0}.b63-tools{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px;align-items:center}.b63-tools input{box-sizing:border-box;height:40px;flex:1 1 220px;min-width:0;border:1px solid #d6ded8;border-radius:10px;padding:0 12px}.b63-table-wrap{width:100%;max-width:100%;overflow-x:auto;overflow-y:hidden;border:1px solid #e5ebe6;border-radius:14px;-webkit-overflow-scrolling:touch;overscroll-behavior-x:contain}.b63-table{width:100%;min-width:860px;border-collapse:separate;border-spacing:0;table-layout:fixed}.b63-table th,.b63-table td{box-sizing:border-box;padding:11px 10px;border-bottom:1px solid #edf0ed;text-align:left;font-size:12px;vertical-align:middle;line-height:1.35;overflow:hidden}.b63-table th{font-size:10px;color:#6d776f;text-transform:uppercase;white-space:nowrap}.b63-table th:nth-child(1),.b63-table td:nth-child(1){width:145px}.b63-table th:nth-child(2),.b63-table td:nth-child(2){width:92px;white-space:nowrap}.b63-table th:nth-child(3),.b63-table td:nth-child(3){width:95px;white-space:nowrap}.b63-table th:nth-child(4),.b63-table td:nth-child(4){width:120px;white-space:nowrap}.b63-table th:nth-child(5),.b63-table td:nth-child(5){width:120px;white-space:nowrap}.b63-table th:nth-child(6),.b63-table td:nth-child(6){width:120px;white-space:nowrap}.b63-table th:nth-child(7),.b63-table td:nth-child(7){width:170px;white-space:normal;overflow-wrap:anywhere;word-break:break-word}.b63-table th:nth-child(8),.b63-table td:nth-child(8){width:150px}.b63-table tr:last-child td{border-bottom:0}.b63-table td strong{display:block;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.b63-table td .b63-phone{display:block;max-width:100%;margin-top:3px;color:#718078;font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.b63-amount,.b63-balance{font-weight:850}.b63-amount{color:#0a7748}.b63-actions{white-space:nowrap!important;overflow:visible!important}.b63-actions button{margin:0 4px 4px 0;white-space:nowrap}.b63-empty{padding:28px;text-align:center;color:#6d776f;border:1px dashed #d6ded8;border-radius:14px}.b63-badge{display:inline-block;flex:0 0 auto;padding:4px 8px;border-radius:999px;background:#edf8f1;color:#0d5b45;font-size:10px;font-weight:800}@media(max-width:600px){.b63-table{min-width:860px}.b63-tools input{flex-basis:100%}.b63-table-wrap{touch-action:pan-x}.b63-table th,.b63-table td{padding:10px 8px}}
` ;document.head.appendChild(s)}
function render(){if(rendering)return;const box=document.getElementById('debtTable');if(!box)return;rendering=true;kind=activeKind();const filtered=rows.filter(r=>r.kind===kind);box.querySelector('.b63-history')?.remove();box.querySelectorAll('.empty').forEach(el=>el.remove());box.querySelectorAll('table:not(.b63-table)').forEach(el=>el.closest('.table-wrap')?.remove()||el.remove());const wrap=document.createElement('div');wrap.className='b63-history';wrap.innerHTML='<div class="b63-tools"><input id="b63Search" type="search" placeholder="Cari nama / referensi..."><span class="b63-badge">'+(kind==='piutang'?'Piutang Pelanggan':'Utang Supplier')+'</span></div><div id="b63List"></div>';box.appendChild(wrap);const list=wrap.querySelector('#b63List');function paint(query){const q=String(query||'').trim().toLowerCase();const data=filtered.filter(r=>!q||[r.party_name,r.reference_no,r.phone,r.note].some(v=>String(v||'').toLowerCase().includes(q)));if(!data.length){list.innerHTML='<div class="b63-empty">'+(filtered.length?'Data tidak ditemukan.':'Belum ada '+(kind==='piutang'?'piutang pelanggan':'utang supplier')+'.')+'</div>';return}let h='<div class="b63-table-wrap"><table class="b63-table"><thead><tr><th>Nama</th><th>Tanggal</th><th>Jumlah</th><th>Total</th><th>Dibayar</th><th>Sisa</th><th>Keterangan</th><th>Aksi</th></tr></thead><tbody>';data.forEach(r=>{const total=Number(r.total_amount||0),paid=Math.min(total,Math.max(0,Number(r.paid_amount||0))),bal=Math.max(0,total-paid);h+='<tr><td><strong>'+esc(r.party_name)+'</strong><span class="b63-phone">'+esc(r.phone||'')+'</span></td><td>'+esc(date(r.debt_date))+'</td><td>'+esc(r.quantity||1)+' '+esc(r.unit||'Paket')+'</td><td class="b63-amount">'+money(total)+'</td><td>'+money(paid)+'</td><td class="b63-balance">'+money(bal)+'</td><td>'+esc(r.note||r.reference_no||'-')+'</td><td class="b63-actions"><button type="button" class="b44-edit" data-b44-debt-edit="'+esc(r.id)+'">✏️ Edit</button><button type="button" class="btn danger" data-del="'+esc(r.id)+'">Hapus</button></td></tr>'});h+='</tbody></table></div>';list.innerHTML=h}const input=wrap.querySelector('#b63Search');input.addEventListener('input',()=>paint(input.value));paint('');rendering=false}
async function removeDebt(id){const u=await user(),sb=SB();if(!u||!sb)return;if(!confirm('Hapus catatan utang/piutang ini?'))return;const q=await sb.from('debts_receivables').delete().eq('id',id).eq('user_id',u.id);if(q.error){alert('Gagal menghapus: '+q.error.message);return}document.dispatchEvent(new CustomEvent('barokah:debt-changed'));await sync()}
async function sync(){try{rows=await load();render()}catch(e){console.warn('[Barokah] debt history sync',e)}}
function bind(){if(bound)return;bound=true;const p=document.getElementById('page-debt');if(!p){bound=false;return}p.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=b.textContent||'';if(/Piutang Pelanggan|Utang Supplier/i.test(t)){kind=/Utang Supplier/i.test(t)?'utang':'piutang';setTimeout(render,120)}});document.addEventListener('click',e=>{const b=e.target.closest('#debtTable [data-del]');if(b&&!b.dataset.b63Bound){b.dataset.b63Bound='1';e.preventDefault();e.stopPropagation();removeDebt(b.dataset.del)}});document.addEventListener('barokah:debt-changed',()=>setTimeout(sync,80));window.addEventListener('focus',()=>setTimeout(sync,100));setInterval(()=>{if(document.getElementById('page-debt')?.classList.contains('active'))sync()},5000)}
function boot(){css();bind();sync()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();