(function(){
  'use strict';
  const TABLES={transaction:['transactions'],debt:['debts_receivables'],operational:['operational_transactions','operational_expenses','operational_records']};
  function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
  function money(v){const n=Number(v||0);return Number.isFinite(n)?'Rp '+n.toLocaleString('id-ID'):esc(v);}
  function date(v){if(!v)return '-';const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'});}
  function val(r,keys){for(const k of keys)if(r&&r[k]!==undefined&&r[k]!==null&&r[k]!=='')return r[k];return '';}
  async function getClient(){for(let i=0;i<50;i++){if(window.barokahSupabase)return window.barokahSupabase;await new Promise(r=>setTimeout(r,100));}throw new Error('Supabase client belum siap.');}
  async function getUser(sb){const s=await sb.auth.getSession();if(s.data?.session?.user)return s.data.session.user;const u=await sb.auth.getUser();if(u.data?.user)return u.data.user;throw new Error('Sesi login tidak ditemukan. Silakan login kembali.');}
  async function queryCandidates(sb,names,userId){let last=null;for(const table of names){try{const q=await sb.from(table).select('*').eq('user_id',userId).order('created_at',{ascending:false}).limit(100);if(!q.error)return{table,rows:q.data||[]};last=q.error;}catch(e){last=e;}}return{table:null,rows:[],error:last};}
  function renderRows(kind,rows){
    if(!rows.length)return '<div class="ht-empty">Belum ada riwayat.</div>';
    return rows.map(r=>{const amount=val(r,['total_idr','amount_idr','amount','total','nominal','price_idr']);const desc=val(r,['description','note','keterangan','name','customer_name','title','category'])||'-';const type=val(r,['type','transaction_type','kind','status']);const dv=val(r,['created_at','transaction_date','date','service_date']);const extra=kind==='debt'?(val(r,['person_name','customer_name','supplier_name','party_name','name'])||'-'):kind==='operational'?(val(r,['category','type','payment_method'])||'-'):(val(r,['unit','quantity','qty'])!==''?String(val(r,['unit','quantity','qty'])):'');return '<div class="ht-row"><div class="ht-main"><strong>'+esc(desc)+'</strong><small>'+esc(date(dv))+'</small></div><div class="ht-meta"><span>'+esc(extra)+'</span><b>'+money(amount)+'</b>'+(type?'<small>'+esc(type)+'</small>':'')+'</div></div>';}).join('');
  }
  function panel(id,title,kind,accent){return '<section class="ht-panel" id="'+id+'" data-kind="'+kind+'" data-accent="'+accent+'"><div class="ht-head"><div><span class="eyebrow">RIWAYAT</span><h3>'+title+'</h3></div><button class="btn ghost ht-refresh" type="button">↻ Refresh</button></div><div class="ht-body"><div class="ht-loading">Memuat data...</div></div></section>';}
  function inject(){
    const page=document.getElementById('page-history');if(!page||document.getElementById('historyColumnsV7040'))return false;
    const anchor=page.querySelector('.list-card');if(!anchor)return false;
    const wrap=document.createElement('div');wrap.id='historyColumnsV7040';
    wrap.innerHTML='<style id="historyColumnsV7040Style">#historyColumnsV7040{margin-top:18px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.ht-panel{background:#fff;border:1px solid var(--line);border-radius:20px;box-shadow:var(--shadow);overflow:hidden;min-width:0}.ht-head{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:16px;border-bottom:1px solid var(--line)}.ht-head h3{margin:4px 0 0;font-size:16px}.ht-body{padding:0}.ht-row{display:grid;grid-template-columns:minmax(0,1fr);gap:8px;padding:13px 15px;border-bottom:1px solid #edf0ed}.ht-row:last-child{border-bottom:0}.ht-main strong,.ht-main small,.ht-meta span,.ht-meta b,.ht-meta small{display:block}.ht-main strong{font-size:13px}.ht-main small,.ht-meta span,.ht-meta small{font-size:11px;color:var(--muted);margin-top:4px}.ht-meta{text-align:left}.ht-meta b{font-size:13px;color:var(--green2);margin-top:5px}.ht-empty,.ht-loading{padding:28px 15px;text-align:center;color:var(--muted);font-size:12px}.ht-error{padding:18px 15px;color:var(--red);font-size:12px}.ht-count{padding:10px 15px;font-size:10px;color:var(--muted);border-top:1px solid #edf0ed}.ht-panel[data-accent="debt"] .ht-head{border-top:4px solid #f4c126}.ht-panel[data-accent="operational"] .ht-head{border-top:4px solid #8a918b}.ht-panel[data-accent="transaction"] .ht-head{border-top:4px solid #24a36b}@media(max-width:950px){#historyColumnsV7040{grid-template-columns:1fr 1fr}.ht-panel:last-child{grid-column:1/-1}}@media(max-width:600px){#historyColumnsV7040{grid-template-columns:1fr}.ht-panel:last-child{grid-column:auto}.ht-head{align-items:flex-start}.ht-head .btn{padding:9px 10px;font-size:11px}}</style>'+panel('ht-transactions','1. Riwayat Transaksi','transaction','transaction')+panel('ht-debts','2. Riwayat Utang Piutang','debt','debt')+panel('ht-operational','3. Riwayat Operasional','operational','operational');
    anchor.insertAdjacentElement('afterend',wrap);
    wrap.querySelectorAll('.ht-refresh').forEach(btn=>btn.addEventListener('click',()=>loadPanel(btn.closest('.ht-panel').id)));
    return true;
  }
  async function loadPanel(id){const p=document.getElementById(id);if(!p)return;const body=p.querySelector('.ht-body'),kind=p.dataset.kind;body.innerHTML='<div class="ht-loading">Memuat data...</div>';try{const sb=await getClient(),user=await getUser(sb),result=await queryCandidates(sb,TABLES[kind],user.id);if(result.error){body.innerHTML='<div class="ht-error">Riwayat belum tersedia: '+esc(result.error.message||'Gagal membaca data')+'</div>';return;}body.innerHTML=renderRows(kind,result.rows)+'<div class="ht-count">Maksimal 100 data terbaru</div>';}catch(e){body.innerHTML='<div class="ht-error">Gagal memuat riwayat: '+esc(e.message||e)+'</div>';}}
  async function boot(){for(let i=0;i<60;i++){if(inject())break;await new Promise(r=>setTimeout(r,100));}if(document.getElementById('historyColumnsV7040')){await Promise.all(['ht-transactions','ht-debts','ht-operational'].map(loadPanel));const nav=document.getElementById('nav-history');if(nav)nav.addEventListener('click',()=>setTimeout(()=>Promise.all(['ht-transactions','ht-debts','ht-operational'].map(loadPanel)),150));}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
