(function(){'use strict';
const SB=()=>window.barokahSupabase;
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
const digits=v=>String(v??'').replace(/\D/g,'');
const dateNow=()=>new Date().toISOString().slice(0,10);
let timer=null,running=false,started=false,modal=null;
async function getSessionUser(){const sb=SB();if(!sb)return null;const s=await sb.auth.getSession();if(s.error)throw s.error;if(s.data?.session?.user)return s.data.session.user;const u=await sb.auth.getUser();return u?.data?.user||null;}
function setStatus(text){const box=document.getElementById('opTable');if(box&&!box.querySelector('table'))box.innerHTML='<div class="op-empty">'+esc(text)+'</div>';}
function css(){if(document.getElementById('opEditPrintFixCss'))return;const s=document.createElement('style');s.id='opEditPrintFixCss';s.textContent='.op-fix-actions{display:flex;gap:4px;flex-wrap:wrap}.op-print-modal{display:none;position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.5)}.op-print-modal.show{display:flex;align-items:center;justify-content:center}.op-edit-modal{background:#fff;border-radius:12px;padding:20px;max-width:600px;width:90%}'document.head.appendChild(s);}
function ensureModal(){if(modal)return modal;modal=document.createElement('div');modal.className='op-print-modal';modal.innerHTML='<div class="op-edit-modal"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;"><h3>Edit Operasional</h3><button onclick="closeModal()" style="border:0;background:#eee;width:32px;height:32px;border-radius:8px;cursor:pointer;">×</button></div><div id="opEditContent"></div></div>';document.body.appendChild(modal);return modal;}
function closeModal(){if(modal)modal.classList.remove('show');}
async function editOperational(id){try{const u=await getSessionUser();if(!u)throw new Error('Sesi login tidak aktif.');const {data:r,error}=await SB().from('operational_transactions').select('*').eq('id',id).eq('user_id',u.id).single();if(error)throw error;const m=ensureModal(),c=m.querySelector('#opEditContent');c.innerHTML='ID: '+esc(r.id)+' | Jenis: '+esc(r.kind)+' | Jumlah: '+fmt(r.amount);m.classList.add('show');}catch(err){console.error(err);alert('Edit gagal: '+(err.message||err));}}
function printOperational(rows){const data=rows||[];const tin=data.filter(x=>x.kind==='pemasukan').reduce((s,x)=>s+Number(x.amount||0),0),tout=data.filter(x=>x.kind==='pengeluaran').reduce((s,x)=>s+Number(x.amount||0),0);alert('Operasional Report\nMasuk: '+fmt(tin)+'\nKeluar: '+fmt(tout));}
async function printAll(){try{const u=await getSessionUser();if(!u)throw new Error('Sesi login tidak aktif.');const {data,error}=await SB().from('operational_transactions').select('*').eq('user_id',u.id);if(error)throw error;printOperational(data);}catch(err){console.error(err);alert('Print gagal: '+(err.message||err));}}
function bindButtons(){const box=document.getElementById('opTable');if(!box)return;box.querySelectorAll('[data-op-del]').forEach(del=>{const cell=del.parentElement;if(!cell||cell.querySelector('[data-op-deleting]'))return;const delBtn=document.createElement('button');delBtn.setAttribute('data-op-deleting','1');delBtn.textContent='Hapus';delBtn.style.fontSize='12px';cell.appendChild(delBtn);});}
async function sync(){if(running)return;const page=document.getElementById('page-operational'),box=document.getElementById('opTable');if(!page||!page.classList.contains('active')||!box)return;running=true;try{const u=await getSessionUser();if(!u){setStatus('Belum login');running=false;return;}const {data,error}=await SB().from('operational_transactions').select('*').eq('user_id',u.id).order('created_at',{ascending:false});if(error)throw error;if(!data||!data.length){setStatus('Tidak ada data operasional');running=false;return;}let html='<table style="width:100%;border-collapse:collapse;font-size:12px;"><tr style="background:#f0f0f0;"><th style="padding:8px;border:1px solid #ddd;text-align:left;">Tanggal</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Jenis</th><th style="padding:8px;border:1px solid #ddd;text-align:right;">Jumlah</th></tr>';data.forEach(r=>{html+='<tr><td style="padding:8px;border:1px solid #ddd;">'+esc(r.created_at||'-')+'</td><td style="padding:8px;border:1px solid #ddd;">'+esc(r.kind||'-')+'</td><td style="padding:8px;border:1px solid #ddd;text-align:right;">'+fmt(r.amount||0)+'</td></tr>';});html+='</table>';box.innerHTML=html;bindButtons();}catch(err){console.error(err);setStatus('Error: '+(err.message||err));}finally{running=false;}}
function start(){if(started)return;started=true;css();sync();timer=setInterval(sync,5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync();});window.addEventListener('beforeunload',()=>{if(timer)clearInterval(timer);});}
window.BarokahOperationalSync={sync,start,editOperational,printAll};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
