(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const factor=u=>{const k=String(u||'').trim().toLowerCase();if(k==='papan')return 30;if(k==='ikat')return 180;return 1;};
  const fmt=n=>Number(n||0).toLocaleString('id-ID',{maximumFractionDigits:3,useGrouping:true});
  const parseNum=v=>{let s=String(v??'').trim().replace(/\s/g,'');if(!s)return NaN;if(s.includes(','))return Number(s.replace(/\./g,'').replace(',','.'));const p=s.split('.');return p.length===1?Number(s):(p[1].length===3?Number(p[0]+p[1]):Number(s));};
  async function getUser(){const sb=window.barokahSupabase;if(!sb)throw new Error('Supabase belum siap.');const r=await sb.auth.getUser();if(r.error)throw r.error;if(!r.data.user)throw new Error('Sesi login tidak ditemukan. Silakan login ulang.');return r.data.user;}
  async function getRows(){const sb=window.barokahSupabase,u=await getUser();const r=await sb.from('stock_movements').select('*').eq('user_id',u.id).order('created_at',{ascending:true}).order('id',{ascending:true});if(r.error)throw r.error;return {sb,u,rows:r.data||[]};}
  function ensureStyle(){if($('stockEditDeleteStyle'))return;const s=document.createElement('style');s.id='stockEditDeleteStyle';s.textContent='.stock-actions{display:flex;gap:6px;flex-wrap:wrap;min-width:140px}.stock-actions button{border:1px solid #dce5df;border-radius:8px;padding:7px 9px;background:#fff;font-size:11px;font-weight:800;cursor:pointer}.stock-edit{color:#14532d}.stock-delete{color:#b42318;background:#fff5f4!important;border-color:#f1d0cc!important}#stockEditModal{display:none;position:fixed;inset:0;z-index:99999;background:rgba(15,23,42,.5);padding:18px;align-items:center;justify-content:center}#stockEditModal.open{display:flex}.stock-edit-card{width:min(520px,100%);background:#fff;border-radius:20px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.25)}.stock-edit-head{display:flex;justify-content:space-between;align-items:center}.stock-edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.stock-edit-grid .full{grid-column:1/-1}.stock-edit-field{display:grid;gap:6px}.stock-edit-field label{font-size:12px;font-weight:800}.stock-edit-field input,.stock-edit-field select{height:42px;border:1px solid #d6ded8;border-radius:10px;padding:0 11px;background:#fff}.stock-edit-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.stock-edit-message{font-size:12px;color:#b42318;min-height:18px;margin-top:8px}.stock-edit-error{background:#fff1f0;border:1px solid #f0c9c5;border-radius:10px;padding:10px;margin-top:10px}@media(max-width:600px){.stock-edit-grid{grid-template-columns:1fr}.stock-edit-grid .full{grid-column:auto}.stock-actions{min-width:0}}';document.head.appendChild(s);}
  function ensureModal(){if($('stockEditModal'))return;ensureStyle();const m=document.createElement('div');m.id='stockEditModal';m.innerHTML='<div class="stock-edit-card"><div class="stock-edit-head"><div><span class="eyebrow">STOK GUDANG</span><h3 style="margin:4px 0 0">Edit Perubahan Stok</h3></div><button type="button" id="stockEditClose" class="btn ghost">×</button></div><div class="stock-edit-grid"><div class="stock-edit-field"><label>Jenis</label><select id="stockEditType"><option>Masuk</option><option>Keluar</option><option>Retak</option><option>Tidak Layak</option></select></div><div class="stock-edit-field"><label>Jumlah</label><input id="stockEditQty" inputmode="decimal" placeholder="Contoh: 10"></div><div class="stock-edit-field"><label>Satuan</label><input id="stockEditUnit" list="stockUnitList" placeholder="Butir / Papan / Ikat"></div><div class="stock-edit-field full"><label>Keterangan</label><input id="stockEditNote" maxlength="150" placeholder="Keterangan stok"></div></div><div id="stockEditMessage" class="stock-edit-message"></div><div id="stockEditError" class="stock-edit-error" style="display:none"></div><div class="stock-edit-actions"><button class="btn ghost" type="button" id="stockEditCancel">Batal</button><button class="btn primary" type="button" id="stockEditSave">Simpan Perubahan</button></div></div>';document.body.appendChild(m);$('stockEditClose').onclick=closeModal;$('stockEditCancel').onclick=closeModal;$('stockEditSave').onclick=saveEdit;}
  let editingId=null;
  function closeModal(){editingId=null;$('stockEditModal')?.classList.remove('open');}
  function openModal(row){ensureModal();editingId=row.id;$('stockEditType').value=row.movement_type||'Masuk';$('stockEditQty').value=String(row.qty??'');$('stockEditUnit').value=row.unit||'Butir';$('stockEditNote').value=row.note||'';$('stockEditMessage').textContent='';$('stockEditError').style.display='none';$('stockEditError').textContent='';$('stockEditModal').classList.add('open');}
  async function saveEdit(){const msg=$('stockEditMessage'),errBox=$('stockEditError'),btn=$('stockEditSave');if(!editingId)return;btn.disabled=true;msg.textContent='Menyimpan...';errBox.style.display='none';try{const {sb,u,rows}=await getRows();const target=rows.find(r=>String(r.id)===String(editingId));if(!target)throw new Error('Data stok tidak ditemukan.');const type=$('stockEditType').value,qty=parseNum($('stockEditQty').value),unit=$('stockEditUnit').value.trim(),note=$('stockEditNote').value.trim();if(!Number.isFinite(qty)||qty<=0)throw new Error('Jumlah harus lebih dari 0.');if(!unit)throw new Error('Satuan wajib diisi.');if((type==='Masuk'||type==='Keluar')&&!note)throw new Error('Keterangan wajib diisi untuk stok masuk/keluar.');const delta=(type==='Masuk'?1:-1)*qty*factor(unit);const idx=rows.findIndex(r=>String(r.id)===String(editingId));const updated=rows.map((r,i)=>i===idx?{...r,movement_type:type,qty,unit,note,delta_butir:delta}:r);let saldo=0;for(const r of updated){saldo+=Number(r.delta_butir||0);if(saldo<0)throw new Error('Edit dibatalkan karena membuat stok menjadi minus.');}
      const payload={movement_type:type,qty,unit,note,delta_butir:delta};
      const one=await sb.from('stock_movements').update(payload).eq('id',target.id).eq('user_id',u.id).select('*');
      if(one.error)throw one.error;
      if(!Array.isArray(one.data)||one.data.length!==1)throw new Error('Data stok tidak ditemukan atau tidak memiliki izin untuk diedit.');
      saldo=0;
      for(const r of updated){saldo+=Number(r.delta_butir||0);const q=await sb.from('stock_movements').update({saldo_after_butir:saldo}).eq('id',r.id).eq('user_id',u.id);if(q.error)throw q.error;}
      closeModal();if(typeof window.renderStock==='function')await window.renderStock();if(typeof window.toast==='function')window.toast('Stok berhasil diperbarui.');
    }catch(e){console.error('[STOK EDIT]',e);msg.textContent='Gagal menyimpan perubahan.';errBox.textContent=e?.message||String(e);errBox.style.display='block';}
    finally{btn.disabled=false;}}
  async function removeOne(id){try{const {sb,u,rows}=await getRows();const target=rows.find(r=>String(r.id)===String(id));if(!target)return alert('Data stok tidak ditemukan.');if(!confirm('Hapus satu riwayat stok ini?\n\n'+(target.movement_type||'')+' '+fmt(target.qty)+' '+(target.unit||'')))return;const r=await sb.from('stock_movements').delete().eq('id',id).eq('user_id',u.id).select('id');if(r.error)throw r.error;if(!Array.isArray(r.data)||r.data.length!==1)throw new Error('Data stok tidak ditemukan atau tidak memiliki izin untuk dihapus.');const left=rows.filter(x=>String(x.id)!==String(id));let saldo=0;for(const x of left){saldo+=Number(x.delta_butir||0);const q=await sb.from('stock_movements').update({saldo_after_butir:saldo}).eq('id',x.id).eq('user_id',u.id);if(q.error)throw q.error;}if(typeof window.renderStock==='function')await window.renderStock();if(typeof window.toast==='function')window.toast('Satu riwayat stok berhasil dihapus.');}catch(e){alert('Gagal menghapus stok: '+(e?.message||e));}}
  async function enhance(){const box=$('stockHistory');if(!box)return;ensureModal();const table=box.querySelector('table.stock-history-table')||box.querySelector('table');if(!table)return;const body=table.querySelector('tbody');if(!body)return;const {rows}=await getRows();const ordered=rows.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)||String(b.id).localeCompare(String(a.id)));const head=table.querySelector('thead tr');if(head&&!head.querySelector('.stock-action-head')){const th=document.createElement('th');th.className='stock-action-head';th.textContent='Aksi';head.appendChild(th);}const trs=[...body.querySelectorAll('tr')];trs.forEach((tr,i)=>{const r=ordered[i];if(!r)return;if(tr.dataset.stockActionId===String(r.id))return;tr.dataset.stockActionId=String(r.id);const old=tr.querySelector('.stock-actions');if(old)old.closest('td')?.remove();const td=document.createElement('td');td.innerHTML='<div class="stock-actions"><button class="stock-edit" type="button">✏️ Edit</button><button class="stock-delete" type="button">🗑️ Hapus</button></div>';td.querySelector('.stock-edit').addEventListener('click',()=>openModal(r));td.querySelector('.stock-delete').addEventListener('click',()=>removeOne(r.id));tr.appendChild(td);});}
  function start(){const box=$('stockHistory');if(!box)return;ensureModal();const obs=new MutationObserver(()=>setTimeout(()=>enhance().catch(e=>console.error('[STOK ACTIONS]',e)),120));obs.observe(box,{childList:true,subtree:true});setTimeout(()=>enhance().catch(e=>console.error('[STOK ACTIONS]',e)),300);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
  window.addEventListener('barokah:supabase-ready',()=>setTimeout(()=>enhance().catch(()=>{}),500));
})();