(function(){
'use strict';
const $=id=>document.getElementById(id);
const factor=u=>{const k=String(u||'').trim().toLowerCase();return k==='papan'?30:k==='ikat'?180:1;};
const parseNum=v=>{let s=String(v??'').trim().replace(/\s/g,'');if(!s)return NaN;if(s.includes(','))return Number(s.replace(/\./g,'').replace(',','.'));const p=s.split('.');return p.length===1?Number(s):(p[1].length===3?Number(p[0]+p[1]):Number(s));};
async function user(){const sb=window.barokahSupabase;if(!sb)throw Error('Supabase belum siap.');const r=await sb.auth.getUser();if(r.error)throw r.error;if(!r.data.user)throw Error('Sesi login tidak ditemukan.');return r.data.user;}
async function rows(){const sb=window.barokahSupabase,u=await user();const r=await sb.from('stock_movements').select('*').eq('user_id',u.id).order('created_at',{ascending:true}).order('id',{ascending:true});if(r.error)throw r.error;return {sb,u,rows:r.data||[]};}
function style(){if($('stockEditDeleteStyle52'))return;const s=document.createElement('style');s.id='stockEditDeleteStyle52';s.textContent='.stock-actions{display:flex;gap:6px;flex-wrap:wrap;min-width:140px}.stock-actions button{border:1px solid #dce5df;border-radius:8px;padding:7px 9px;background:#fff;font-size:11px;font-weight:800;cursor:pointer}.stock-edit{color:#14532d}.stock-delete{color:#b42318;background:#fff5f4!important;border-color:#f1d0cc!important}#stockEditModal52{display:none;position:fixed;inset:0;z-index:99999;background:rgba(15,23,42,.5);padding:18px;align-items:center;justify-content:center}#stockEditModal52.open{display:flex}.stock-edit-card52{width:min(520px,100%);background:#fff;border-radius:20px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.25)}.stock-edit-grid52{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.stock-edit-grid52 .full{grid-column:1/-1}.stock-edit-field52{display:grid;gap:6px}.stock-edit-field52 label{font-size:12px;font-weight:800}.stock-edit-field52 input,.stock-edit-field52 select{height:42px;border:1px solid #d6ded8;border-radius:10px;padding:0 11px;background:#fff}.stock-edit-actions52{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.stock-edit-error52{font-size:12px;color:#b42318;margin-top:8px}.stock-edit-head52{display:flex;justify-content:space-between;align-items:center}@media(max-width:600px){.stock-edit-grid52{grid-template-columns:1fr}.stock-edit-grid52 .full{grid-column:auto}.stock-actions{min-width:0}}';document.head.appendChild(s);}
function modal(){if($('stockEditModal52'))return;style();const m=document.createElement('div');m.id='stockEditModal52';m.innerHTML='<div class="stock-edit-card52"><div class="stock-edit-head52"><div><small>STOK GUDANG</small><h3 style="margin:4px 0">Edit Perubahan Stok</h3></div><button type="button" id="stockClose52" class="btn ghost">×</button></div><div class="stock-edit-grid52"><div class="stock-edit-field52"><label>Jenis</label><select id="stockType52"><option>Masuk</option><option>Keluar</option><option>Retak</option><option>Tidak Layak</option></select></div><div class="stock-edit-field52"><label>Jumlah</label><input id="stockQty52" inputmode="decimal"></div><div class="stock-edit-field52"><label>Satuan</label><input id="stockUnit52" placeholder="Butir / Papan / Ikat"></div><div class="stock-edit-field52 full"><label>Keterangan</label><input id="stockNote52" maxlength="150"></div></div><div id="stockErr52" class="stock-edit-error52"></div><div class="stock-edit-actions52"><button type="button" id="stockCancel52" class="btn ghost">Batal</button><button type="button" id="stockSave52" class="btn primary">Simpan Perubahan</button></div></div>';document.body.appendChild(m);$('stockClose52').onclick=close;$('stockCancel52').onclick=close;$('stockSave52').onclick=save;}
let editId=null;function close(){editId=null;$('stockEditModal52')?.classList.remove('open');}
function open(r){modal();editId=r.id;$('stockType52').value=r.movement_type||'Masuk';$('stockQty52').value=r.qty??'';$('stockUnit52').value=r.unit||'Butir';$('stockNote52').value=r.note||'';$('stockErr52').textContent='';$('stockEditModal52').classList.add('open');}
async function save(){if(!editId)return;const btn=$('stockSave52');btn.disabled=true;$('stockErr52').textContent='Menyimpan...';try{const {sb,u,rows:r}=await rows();const target=r.find(x=>String(x.id)===String(editId));if(!target)throw Error('Data stok tidak ditemukan.');const type=$('stockType52').value,qty=parseNum($('stockQty52').value),unit=$('stockUnit52').value.trim(),note=$('stockNote52').value.trim();if(!Number.isFinite(qty)||qty<=0)throw Error('Jumlah harus lebih dari 0.');if(!unit)throw Error('Satuan wajib diisi.');const delta=(type==='Masuk'?1:-1)*qty*factor(unit);const updated=r.map(x=>String(x.id)===String(editId)?{...x,movement_type:type,qty,unit,note,delta_butir:delta}:x);let saldo=0;for(const x of updated){saldo+=Number(x.delta_butir||0);if(saldo<0)throw Error('Edit dibatalkan karena membuat stok menjadi minus.');}
 const u1=await sb.from('stock_movements').update({movement_type:type,qty,unit,note,delta_butir:delta}).eq('id',target.id).eq('user_id',u.id);if(u1.error)throw u1.error;
 const verify=await sb.from('stock_movements').select('id,movement_type,qty,unit,note,delta_butir').eq('id',target.id).eq('user_id',u.id);if(verify.error)throw verify.error;if(!verify.data?.length)throw Error('Perubahan tersimpan tetapi data tidak dapat diverifikasi. Cek izin SELECT pada stock_movements.');
 saldo=0;for(const x of updated){saldo+=Number(x.delta_butir||0);const q=await sb.from('stock_movements').update({saldo_after_butir:saldo}).eq('id',x.id).eq('user_id',u.id);if(q.error)throw q.error;}
 close();if(typeof window.renderStock==='function')await window.renderStock();if(typeof window.toast==='function')window.toast('Stok berhasil diperbarui.');else alert('Stok berhasil diperbarui.');
 }catch(e){console.error('[STOK EDIT 52]',e);$('stockErr52').textContent=e?.message||String(e);}finally{btn.disabled=false;}}
async function remove(id){try{const {sb,u,rows:r}=await rows();const target=r.find(x=>String(x.id)===String(id));if(!target)return alert('Data stok tidak ditemukan.');if(!confirm('Hapus satu riwayat stok ini?'))return;const d=await sb.from('stock_movements').delete().eq('id',id).eq('user_id',u.id);if(d.error)throw d.error;const verify=await sb.from('stock_movements').select('id').eq('id',id).eq('user_id',u.id);if(verify.error)throw verify.error;if(verify.data?.length)throw Error('Data belum terhapus. Cek izin DELETE pada stock_movements.');const left=r.filter(x=>String(x.id)!==String(id));let saldo=0;for(const x of left){saldo+=Number(x.delta_butir||0);const q=await sb.from('stock_movements').update({saldo_after_butir:saldo}).eq('id',x.id).eq('user_id',u.id);if(q.error)throw q.error;}if(typeof window.renderStock==='function')await window.renderStock();if(typeof window.toast==='function')window.toast('Satu riwayat stok berhasil dihapus.');}catch(e){alert('Gagal menghapus stok: '+(e?.message||e));}}
async function enhance(){const box=$('stockHistory');if(!box)return;modal();const table=box.querySelector('table.stock-history-table')||box.querySelector('table');if(!table)return;const body=table.querySelector('tbody');if(!body)return;const {rows:r}=await rows();const ordered=r.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)||String(b.id).localeCompare(String(a.id)));const head=table.querySelector('thead tr');if(head&&!head.querySelector('.stock-action-head52')){const th=document.createElement('th');th.className='stock-action-head52';th.textContent='Aksi';head.appendChild(th);} [...body.querySelectorAll('tr')].forEach((tr,i)=>{const x=ordered[i];if(!x)return;tr.querySelector('.stock-actions')?.closest('td')?.remove();const td=document.createElement('td');td.innerHTML='<div class="stock-actions"><button class="stock-edit" type="button">✏️ Edit</button><button class="stock-delete" type="button">🗑️ Hapus</button></div>';td.querySelector('.stock-edit').onclick=()=>open(x);td.querySelector('.stock-delete').onclick=()=>remove(x.id);tr.appendChild(td);});}
function start(){const box=$('stockHistory');if(!box)return;modal();const run=()=>setTimeout(()=>enhance().catch(e=>console.error('[STOK ACTIONS 52]',e)),200);new MutationObserver(run).observe(box,{childList:true,subtree:true});run();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('barokah:supabase-ready',()=>setTimeout(()=>enhance().catch(()=>{}),500));
})();