(function(){
'use strict';
const $=id=>document.getElementById(id);
const factor=u=>{const k=String(u||'').trim().toLowerCase();return k==='papan'?30:k==='ikat'?180:1;};
const fmt=n=>Number(n||0).toLocaleString('id-ID',{maximumFractionDigits:10,useGrouping:true});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const parseNum=v=>{let s=String(v??'').trim().replace(/\s/g,'');if(!s)return NaN;if(s.includes(','))return Number(s.replace(/\./g,'').replace(',','.'));const p=s.split('.');return p.length===1?Number(s):(p[1].length===3?Number(p[0]+p[1]):Number(s));};
async function ctx(){const sb=window.barokahSupabase;if(!sb)throw Error('Supabase belum siap.');const ur=await sb.auth.getUser();if(ur.error)throw ur.error;if(!ur.data.user)throw Error('Sesi login tidak ditemukan.');const r=await sb.from('stock_movements').select('*').eq('user_id',ur.data.user.id).order('created_at',{ascending:true}).order('id',{ascending:true});if(r.error)throw r.error;return {sb,u:ur.data.user,rows:r.data||[]};}
function saldo(rows){return rows.reduce((n,r)=>n+Number(r.delta_butir||0),0);}
function running(rows){let s=0;return rows.map(r=>{s+=Number(r.delta_butir||0);return {...r,calculated_saldo_after_butir:s};});}
function styles(){if($('stockIntegratedStyle53'))return;const s=document.createElement('style');s.id='stockIntegratedStyle53';s.textContent=`#stockIntegratedModal53{display:none;position:fixed;inset:0;z-index:100000;background:rgba(15,23,42,.55);align-items:center;justify-content:center;padding:18px}#stockIntegratedModal53.open{display:flex}.stock53-card{width:min(520px,100%);background:#fff;border-radius:20px;padding:20px;box-shadow:0 24px 80px rgba(0,0,0,.25)}.stock53-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.stock53-grid .full{grid-column:1/-1}.stock53-field{display:grid;gap:6px}.stock53-field label{font-size:12px;font-weight:800}.stock53-field input,.stock53-field select{height:42px;border:1px solid #d6ded8;border-radius:10px;padding:0 11px}.stock53-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.stock53-error{margin-top:9px;color:#b42318;font-size:12px}.stock53-row-actions{display:flex;gap:6px;flex-wrap:wrap;min-width:145px}.stock53-row-actions button{border:1px solid #dce5df;border-radius:8px;padding:7px 9px;background:#fff;font-size:11px;font-weight:800;cursor:pointer}.stock53-edit{color:#14532d}.stock53-delete{color:#b42318;background:#fff5f4!important;border-color:#f1d0cc!important}@media(max-width:600px){.stock53-grid{grid-template-columns:1fr}.stock53-grid .full{grid-column:auto}.stock53-row-actions{min-width:0}}`;document.head.appendChild(s);}
function modal(){if($('stockIntegratedModal53'))return;styles();const m=document.createElement('div');m.id='stockIntegratedModal53';m.innerHTML=`<div class="stock53-card"><div style="display:flex;justify-content:space-between;align-items:center"><div><small>STOK GUDANG</small><h3 style="margin:4px 0">Edit Perubahan Stok</h3></div><button type="button" id="stock53Close" class="btn ghost">×</button></div><div class="stock53-grid"><div class="stock53-field"><label>Jenis</label><select id="stock53Type"><option>Masuk</option><option>Keluar</option><option>Retak</option><option>Tidak Layak</option></select></div><div class="stock53-field"><label>Jumlah</label><input id="stock53Qty" inputmode="decimal"></div><div class="stock53-field"><label>Satuan</label><input id="stock53Unit" placeholder="Butir / Papan / Ikat"></div><div class="stock53-field full"><label>Keterangan</label><input id="stock53Note" maxlength="150"></div></div><div id="stock53Error" class="stock53-error"></div><div class="stock53-actions"><button type="button" id="stock53Cancel" class="btn ghost">Batal</button><button type="button" id="stock53Save" class="btn primary">Simpan Perubahan</button></div></div>`;document.body.appendChild(m);$('stock53Close').onclick=close;$('stock53Cancel').onclick=close;$('stock53Save').onclick=save;}
let editId=null;function close(){editId=null;$('stockIntegratedModal53')?.classList.remove('open');}
function openEdit(row){modal();editId=row.id;$('stock53Type').value=row.movement_type||'Masuk';$('stock53Qty').value=row.qty??'';$('stock53Unit').value=row.unit||'Butir';$('stock53Note').value=row.note||'';$('stock53Error').textContent='';$('stockIntegratedModal53').classList.add('open');}
async function save(){if(!editId)return;const btn=$('stock53Save');btn.disabled=true;$('stock53Error').textContent='Menyimpan...';try{const {sb,rows}=await ctx();const target=rows.find(x=>String(x.id)===String(editId));if(!target)throw Error('Data stok tidak ditemukan.');const type=$('stock53Type').value,qty=parseNum($('stock53Qty').value),unit=$('stock53Unit').value.trim(),note=$('stock53Note').value.trim();if(!Number.isFinite(qty)||qty<=0)throw Error('Jumlah harus lebih dari 0.');if(!unit)throw Error('Satuan wajib diisi.');const delta=(type==='Masuk'?1:-1)*qty*factor(unit);const preview=rows.map(x=>String(x.id)===String(editId)?{...x,movement_type:type,qty,unit,note,delta_butir:delta}:x);let s=0;for(const x of preview){s+=Number(x.delta_butir||0);if(s<0)throw Error('Edit dibatalkan karena membuat stok menjadi minus.');}
const rpc=await sb.rpc('update_own_stock_movement',{p_id:target.id,p_movement_type:type,p_qty:qty,p_unit:unit,p_note:note,p_delta_butir:delta});
if(rpc.error)throw rpc.error;
close();await renderStock();if(typeof window.toast==='function')window.toast('Stok berhasil diperbarui.');else alert('Stok berhasil diperbarui.');
}catch(e){console.error('[STOCK53 EDIT]',e);$('stock53Error').textContent=e?.message||String(e);}finally{btn.disabled=false;}}
async function remove(id){if(!confirm('Hapus satu riwayat stok ini?'))return;try{const {sb,rows}=await ctx();if(!rows.some(x=>String(x.id)===String(id)))throw Error('Data stok tidak ditemukan.');const rpc=await sb.rpc('delete_own_stock_movement',{p_id:id});if(rpc.error)throw rpc.error;await renderStock();if(typeof window.toast==='function')window.toast('Satu riwayat stok berhasil dihapus.');else alert('Stok berhasil dihapus.');}catch(e){alert('Gagal menghapus stok: '+(e?.message||e));}}
async function renderStock(){try{const {rows}=await ctx();const ordered=running(rows);const total=saldo(rows);const w=$('stockWarehouse');if(w)w.textContent=fmt(total)+' Butir';const p=$('stockAutoPreview');if(p)p.textContent='Saldo saat ini: '+fmt(total)+' Butir. Stok tersimpan di database online.';const bad=ordered.filter(r=>r.movement_type==='Retak').reduce((a,r)=>a+Number(r.qty||0)*factor(r.unit),0);const unfit=ordered.filter(r=>r.movement_type==='Tidak Layak').reduce((a,r)=>a+Number(r.qty||0)*factor(r.unit),0);if($('badEggsInfo'))$('badEggsInfo').textContent='Total Telur Retak: '+fmt(bad)+' Butir';if($('unfitEggsInfo'))$('unfitEggsInfo').textContent='Total Telur Tidak Layak: '+fmt(unfit)+' Butir';const box=$('stockHistory');if(!box)return;if(!ordered.length){box.innerHTML='<div class="stock-history-empty">Belum ada riwayat stok.</div>';return;}const html=ordered.slice().reverse().map(r=>{const d=Number(r.delta_butir||0),sign=d>=0?'+':'-',abs=Math.abs(d),conv=abs%30===0?sign+fmt(abs/30)+' Papan | '+sign+fmt(abs)+' Butir':sign+fmt(abs)+' Butir';return `<tr><td>${new Date(r.created_at).toLocaleDateString('id-ID')}</td><td><b>${esc(r.product||'Telur Ayam Ras')}</b></td><td><b>${esc(r.movement_type||'')}</b></td><td>${sign+fmt(Math.abs(Number(r.qty)||0))} ${esc(r.unit||'')}</td><td>${conv}</td><td><b>${fmt(r.calculated_saldo_after_butir)} Butir</b></td><td>${esc(r.note||'-')}</td><td><div class="stock53-row-actions"><button class="stock53-edit" type="button" data-id="${esc(r.id)}">✏️ Edit</button><button class="stock53-delete" type="button" data-id="${esc(r.id)}">🗑️ Hapus</button></div></td></tr>`;}).join('');box.innerHTML=`<div class="stock-table-wrap"><table class="stock-history-table"><thead><tr><th>Tanggal</th><th>Produk</th><th>Jenis</th><th>Jumlah</th><th>Konversi</th><th>Saldo Setelah</th><th>Keterangan</th><th>Aksi</th></tr></thead><tbody>${html}</tbody></table></div>`;box.querySelectorAll('.stock53-edit').forEach(b=>b.onclick=()=>{const r=ordered.find(x=>String(x.id)===String(b.dataset.id));if(r)openEdit(r);});box.querySelectorAll('.stock53-delete').forEach(b=>b.onclick=()=>remove(b.dataset.id));}catch(e){console.error('[STOCK53 RENDER]',e);const box=$('stockHistory');if(box)box.innerHTML='<div class="stock-history-empty">Gagal memuat stok: '+esc(e?.message||e)+'</div>';}}
window.renderStock=renderStock;window.stock53Reload=renderStock;
function start(){modal();if(window.barokahSupabase){setTimeout(renderStock,300);} }
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('barokah:supabase-ready',()=>setTimeout(renderStock,300));
})();