(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const factor=u=>{const k=String(u||'').trim().toLowerCase();if(k==='papan')return 30;if(k==='ikat')return 180;if(k==='butir')return 1;return 1;};
  const fmt=n=>Number(n||0).toLocaleString('id-ID',{maximumFractionDigits:3,useGrouping:true});
  const parseNum=v=>{let s=String(v??'').trim().replace(/\s/g,'');if(!s)return NaN;if(s.includes(','))return Number(s.replace(/\./g,'').replace(',','.'));const p=s.split('.');if(p.length===1)return Number(s);return p[1].length===3?Number(p[0]+p[1]):Number(s);};
  async function user(){const sb=window.barokahSupabase;if(!sb)return null;const r=await sb.auth.getUser();return r.data&&r.data.user?r.data.user:null;}
  async function getRows(){const sb=window.barokahSupabase,u=await user();if(!sb||!u)throw new Error('Sesi database belum aktif.');const r=await sb.from('stock_movements').select('*').eq('user_id',u.id).order('created_at',{ascending:true}).order('id',{ascending:true});if(r.error)throw r.error;return r.data||[];}
  function ensureStyle(){if($('stockEditDeleteStyle'))return;const s=document.createElement('style');s.id='stockEditDeleteStyle';s.textContent=`
    .stock-actions{display:flex;gap:6px;flex-wrap:wrap;min-width:132px}.stock-actions button{border:1px solid #dce5df;border-radius:8px;padding:7px 9px;background:#fff;font-size:11px;font-weight:800;cursor:pointer}.stock-actions .stock-edit{color:#14532d}.stock-actions .stock-delete{color:#b42318;background:#fff5f4;border-color:#f1d0cc}
    #stockEditModal{display:none;position:fixed;inset:0;z-index:99999;background:rgba(15,23,42,.5);padding:18px;align-items:center;justify-content:center}#stockEditModal.open{display:flex}.stock-edit-card{width:min(520px,100%);background:#fff;border-radius:20px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.25)}.stock-edit-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.stock-edit-head h3{margin:0}.stock-edit-close{border:0;background:#eef2ef;width:36px;height:36px;border-radius:10px;font-size:20px}.stock-edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.stock-edit-grid .full{grid-column:1/-1}.stock-edit-field{display:grid;gap:6px}.stock-edit-field label{font-size:12px;font-weight:800}.stock-edit-field input,.stock-edit-field select{height:42px;border:1px solid #d6ded8;border-radius:10px;padding:0 11px;background:#fff}.stock-edit-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.stock-edit-message{font-size:12px;color:#b42318;min-height:18px;margin-top:8px}@media(max-width:600px){.stock-edit-grid{grid-template-columns:1fr}.stock-edit-grid .full{grid-column:auto}.stock-actions{min-width:0}}
  `;document.head.appendChild(s);}
  function ensureModal(){if($('stockEditModal'))return;ensureStyle();const m=document.createElement('div');m.id='stockEditModal';m.innerHTML=`<div class="stock-edit-card"><div class="stock-edit-head"><div><span class="eyebrow">STOK GUDANG</span><h3>Edit Perubahan Stok</h3></div><button class="stock-edit-close" type="button" id="stockEditClose">×</button></div><div class="stock-edit-grid"><div class="stock-edit-field"><label>Jenis</label><select id="stockEditType"><option>Masuk</option><option>Keluar</option><option>Retak</option><option>Tidak Layak</option></select></div><div class="stock-edit-field"><label>Jumlah</label><input id="stockEditQty" inputmode="decimal" placeholder="Contoh: 10"></div><div class="stock-edit-field"><label>Satuan</label><input id="stockEditUnit" list="barokahUnitList" placeholder="Butir / Papan / Ikat"></div><div class="stock-edit-field full"><label>Keterangan</label><input id="stockEditNote" maxlength="150" placeholder="Keterangan stok"></div></div><div id="stockEditMessage" class="stock-edit-message"></div><div class="stock-edit-actions"><button class="btn ghost" type="button" id="stockEditCancel">Batal</button><button class="btn primary" type="button" id="stockEditSave">Simpan Perubahan</button></div></div>`;document.body.appendChild(m);$('stockEditClose').onclick=closeModal;$('stockEditCancel').onclick=closeModal;}
  let editingId=null;
  function closeModal(){editingId=null;$('stockEditModal')?.classList.remove('open');}
  function openModal(r){ensureModal();editingId=r.id;$('stockEditType').value=r.movement_type||'Masuk';$('stockEditQty').value=String(r.qty??'');$('stockEditUnit').value=r.unit||'Butir';$('stockEditNote').value=r.note||'';$('stockEditMessage').textContent='';$('stockEditModal').classList.add('open');}
  async function saveEdit(){const sb=window.barokahSupabase,u=await user();if(!sb||!u||!editingId)return;const type=$('stockEditType').value,qty=parseNum($('stockEditQty').value),unit=$('stockEditUnit').value.trim(),note=$('stockEditNote').value.trim();if(!Number.isFinite(qty)||qty<=0){$('stockEditMessage').textContent='Jumlah harus lebih dari 0.';return;}if(!unit){$('stockEditMessage').textContent='Satuan wajib diisi.';return;}if((type==='Masuk'||type==='Keluar')&&!note){$('stockEditMessage').textContent='Keterangan wajib diisi untuk stok masuk/keluar.';return;}const all=await getRows();const target=all.find(r=>String(r.id)===String(editingId));if(!target){$('stockEditMessage').textContent='Data stok tidak ditemukan.';return;}const sign=type==='Masuk'?1:-1;const delta=qty*factor(unit)*sign;const idx=all.findIndex(r=>String(r.id)===String(editingId));all[idx]={...target,movement_type:type,qty,unit,note,delta_butir:delta};let running=0;for(const r of all){running+=Number(r.delta_butir||0);if(running<0){$('stockEditMessage').textContent='Perubahan ini membuat stok menjadi minus. Edit dibatalkan.';return;}}
    $('stockEditSave').disabled=true;$('stockEditMessage').textContent='Menyimpan...';
    try{
      for(const r of all){const upd=await sb.from('stock_movements').update({movement_type:r.movement_type,qty:r.qty,unit:r.unit,note:r.note,delta_butir:r.delta_butir,saldo_after_butir:0}).eq('id',r.id).eq('user_id',u.id);if(upd.error)throw upd.error;}
      running=0;for(const r of all){running+=Number(r.delta_butir||0);const upd=await sb.from('stock_movements').update({saldo_after_butir:running}).eq('id',r.id).eq('user_id',u.id);if(upd.error)throw upd.error;}
      closeModal();if(typeof window.renderStock==='function')window.renderStock();if(typeof window.toast==='function')window.toast('Stok berhasil diperbarui.');
    }catch(e){$('stockEditMessage').textContent='Gagal menyimpan: '+(e.message||e);}
    finally{$('stockEditSave').disabled=false;}
  }
  async function removeOne(id){const sb=window.barokahSupabase,u=await user();if(!sb||!u)return;const all=await getRows();const target=all.find(r=>String(r.id)===String(id));if(!target){alert('Data stok tidak ditemukan.');return;}const label=`${target.movement_type} ${fmt(target.qty)} ${target.unit}`;if(!confirm('Hapus satu riwayat stok ini?\n\n'+label+'\n\nSaldo setelah data ini akan dihitung ulang.'))return;const r=await sb.from('stock_movements').delete().eq('id',id).eq('user_id',u.id);if(r.error){alert('Gagal menghapus stok: '+r.error.message);return;}const left=all.filter(x=>String(x.id)!==String(id));let running=0;for(const x of left){running+=Number(x.delta_butir||0);const upd=await sb.from('stock_movements').update({saldo_after_butir:running}).eq('id',x.id).eq('user_id',u.id);if(upd.error){alert('Data terhapus, tetapi saldo audit gagal diperbarui: '+upd.error.message);break;}}if(typeof window.renderStock==='function')window.renderStock();if(typeof window.toast==='function')window.toast('Satu riwayat stok berhasil dihapus.');}
  async function enhance(){const box=$('stockHistory');if(!box)return;ensureModal();const table=box.querySelector('table.stock-history-table');if(!table)return;const body=table.querySelector('tbody');if(!body)return;if(body.dataset.stockActionsReady==='1')return;let all;try{all=await getRows();}catch(e){return;}const ordered=all.slice().reverse();const head=table.querySelector('thead tr');if(head&&!head.querySelector('.stock-action-head')){const th=document.createElement('th');th.className='stock-action-head';th.textContent='Aksi';head.appendChild(th);}const trs=[...body.querySelectorAll('tr')];trs.forEach((tr,i)=>{const r=ordered[i];if(!r)return;tr.dataset.stockId=r.id;const td=document.createElement('td');td.innerHTML='<div class="stock-actions"><button class="stock-edit" type="button">✏️ Edit</button><button class="stock-delete" type="button">🗑️ Hapus</button></div>';td.querySelector('.stock-edit').onclick=()=>openModal(r);td.querySelector('.stock-delete').onclick=()=>removeOne(r.id);tr.appendChild(td);});body.dataset.stockActionsReady='1';}
  function watch(){const box=$('stockHistory');if(!box)return;const obs=new MutationObserver(()=>setTimeout(enhance,80));obs.observe(box,{childList:true,subtree:true});setTimeout(enhance,200);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();
  window.addEventListener('barokah:supabase-ready',()=>setTimeout(enhance,250));
  document.addEventListener('click',e=>{if(e.target&&e.target.id==='stockEditSave')saveEdit();});
})();