(function(){
'use strict';
const $=id=>document.getElementById(id);
const factor=u=>{const k=String(u||'').trim().toLowerCase();return k==='papan'?30:k==='ikat'?180:1;};
const parseNum=v=>{let s=String(v??'').trim().replace(/\s/g,'');if(!s)return NaN;if(s.includes(','))return Number(s.replace(/\./g,'').replace(',','.'));const p=s.split('.');return p.length===1?Number(s):(p[1].length===3?Number(p[0]+p[1]):Number(s));};
async function user(){const sb=window.barokahSupabase;if(!sb)throw Error('Supabase belum siap.');const r=await sb.auth.getUser();if(r.error)throw r.error;if(!r.data.user)throw Error('Sesi login tidak ditemukan.');return r.data.user;}
async function rows(){const sb=window.barokahSupabase,u=await user();const r=await sb.from('stock_movements').select('*').eq('user_id',u.id).order('created_at',{ascending:true}).order('id',{ascending:true});if(r.error)throw r.error;return {sb,u,rows:r.data||[]};}
function style(){if($('stockEditDeleteStyle53'))return;const s=document.createElement('style');s.id='stockEditDeleteStyle53';s.textContent='.stock-actions{display:flex;gap:6px;flex-wrap:wrap;min-width:140px}.stock-actions button{border:1px solid #dce5df;border-radius:8px;padding:7px 9px;background:#fff;font-size:11px;font-weight:800;cursor:pointer}.stock-edit{color:#14532d}.stock-delete{color:#b42318;background:#fff5f4!important;border-color:#f1d0cc!important}#stockEditModal53{display:none;position:fixed;inset:0;z-index:99999;background:rgba(15,23,42,.5);padding:18px;align-items:center;justify-content:center}#stockEditModal53.open{display:flex}.stock-edit-card53{width:min(520px,100%);background:#fff;border-radius:20px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.25)}.stock-edit-grid53{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.stock-edit-grid53 .full{grid-column:1/-1}.stock-edit-field53{display:grid;gap:6px}.stock-edit-field53 label{font-size:12px;font-weight:800}.stock-edit-field53 input,.stock-edit-field53 select{height:42px;border:1px solid #d6ded8;border-radius:10px;padding:0 11px;background:#fff}.stock-edit-actions53{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.stock-edit-error53{font-size:12px;color:#b42318;margin-top:8px}.stock-edit-head53{display:flex;justify-content:space-between;align-items:center}@media(max-width:600px){.stock-edit-grid53{grid-template-columns:1fr}.stock-edit-grid53 .full{grid-column:auto}.stock-actions{min-width:0}}';document.head.appendChild(s);}
function modal(){if($('stockEditModal53'))return;style();const m=document.createElement('div');m.id='stockEditModal53';m.innerHTML='<div class="stock-edit-card53"><div class="stock-edit-head53"><div><small>STOK GUDANG</small><h3 style="margin:4px 0">Edit Perubahan Stok</h3></div><button type="button" id="stockClose53" class="btn ghost">×</button></div><div class="stock-edit-grid53"><div class="stock-edit-field53"><label>Jenis</label><select id="stockType53"><option>Masuk</option><option>Keluar</option><option>Retak</option><option>Tidak Layak</option></select></div><div class="stock-edit-field53"><label>Jumlah</label><input id="stockQty53" inputmode="decimal"></div><div class="stock-edit-field53"><label>Satuan</label><input id="stockUnit53" placeholder="Butir / Papan / Ikat"></div><div class="stock-edit-field53 full"><label>Keterangan</label><input id="stockNote53" maxlength="150"></div></div><div id="stockErr53" class="stock-edit-error53"></div><div class="stock-edit-actions53"><button type="button" id="stockCancel53" class="btn ghost">Batal</button><button type="button" id="stockSave53" class="btn primary">Simpan Perubahan</button></div></div>';document.body.appendChild(m);$('stockClose53').onclick=close;$('stockCancel53').onclick=close;$('stockSave53').onclick=save;}
let editId=null;function close(){editId=null;$('stockEditModal53')?.classList.remove('open');}
function open(r){modal();editId=r.id;$('stockType53').value=r.movement_type||'Masuk';$('stockQty53').value=r.qty??'';$('stockUnit53').value=r.unit||'Butir';$('stockNote53').value=r.note||'';$('stockErr53').textContent='';$('stockEditModal53').classList.add('open');}
async function save(){if(!editId)return;const btn=$('stockSave53');btn.disabled=true;$('stockErr53').textContent='Menyimpan...';try{const {sb,u,rows:r}=await rows();const target=r.find(x=>String(x.id)===String(editId));if(!target)throw Error('Data stok tidak ditemukan.');const type=$('stockType53').value,qty=parseNum($('stockQty53').value),unit=$('stockUnit53').value.trim(),note=$('stockNote53').value.trim();if(!Number.isFinite(qty)||qty<=0)throw Error('Jumlah harus lebih dari 0.');if(!unit)throw Error('Satuan wajib diisi.');if((type==='Masuk'||type==='Keluar')&&!note)throw Error('Keterangan wajib diisi untuk stok masuk/keluar.');const delta=(type==='Masuk'?1:-1)*qty*factor(unit);const updated=r.map(x=>String(x.id)===String(editId)?{...x,movement_type:type,qty,unit,note,delta_butir:delta}:x);let saldo=0;for(const x of updated){saldo+=Number(x.delta_butir||0);if(saldo<0)throw Error('Edit dibatalkan karena membuat stok menjadi minus.');}
 const rpc=await sb.rpc('update_own_stock_movement',{p_id:target.id,p_movement_type:type,p_qty:qty,p_unit:unit,p_note:note,p_delta_butir:delta});
 if(rpc.error){const msg=String(rpc.error.message||rpc.error);if(msg.includes('Could not find the function')||msg.includes('schema cache'))throw Error('Fitur edit database belum diaktifkan. Jalankan SQL V70.5.3 di Supabase sekali.');throw rpc.error;}
 saldo=0;for(const x of updated){saldo+=Number(x.delta_butir||0);const q=await sb.from('stock_movements').update({saldo_after_butir:saldo}).eq('id',x.id).eq('user_id',u.id);if(q.error)throw q.error;}
 close();if(typeof window.renderStock==='function')await window.renderStock();if(typeof window.toast==='function')window.toast('Stok berhasil diperbarui.');else alert('Stok berhasil diperbarui.');
 }catch(e){console.error('[STOK EDIT 53]',e);$('stockErr53').textContent='Gagal menyimpan: '+(e?.message||String(e));}finally{btn.disabled=false;}}
async function remove(id){try{const {sb,u,rows:r}=await rows();const target=r.find(x=>String(x.id)===String(id));if(!target)return alert('Data stok tidak ditemukan.');if(!confirm('Hapus satu riwayat stok ini?'))return;const rpc=await sb.rpc('delete_own_stock_movement',{p_id:id});if(rpc.error){const msg=String(rpc.error.message||rpc.error);if(msg.includes('Could not find the function')||msg.includes('schema cache'))throw Error('Fitur hapus database belum diaktifkan. Jalankan SQL V70.5.3 di Supabase sekali.');throw rpc.error;}const left=r.filter(x=>String(x.id)!==String(id));let saldo=0;for(const x of left){saldo+=Number(x.delta_butir||0);const q=await sb.from('stock_movements').update({saldo_after_butir:saldo}).eq('id',x.id).eq('user_id',u.id);if(q.error)throw q.error;}if(typeof window.renderStock==='function')await window.renderStock();if(typeof window.toast==='function')window.toast('Satu riwayat stok berhasil dihapus.');}catch(e){alert('Gagal menghapus stok: '+(e?.message||e));}}
async function enhance(){const box=$('stockHistory');if(!box)return;modal();const table=box.querySelector('table.stock-history-table')||box.querySelector('table');if(!table)return;const body=table.querySelector('tbody');if(!body)return;const {rows:r}=await rows();const ordered=r.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)||String(b.id).localeCompare(String(a.id)));const head=table.querySelector('thead tr');if(head&&!head.querySelector('.stock-action-head53')){const th=document.createElement('th');th.className='stock-action-head53';th.textContent='Aksi';head.appendChild(th);} [...body.querySelectorAll('tr')].forEach((tr,i)=>{const x=ordered[i];if(!x)return;tr.querySelector('.stock-actions')?.closest('td')?.remove();const td=document.createElement('td');td.innerHTML='<div class="stock-actions"><button class="stock-edit" type="button">✏️ Edit</button><button class="stock-delete" type="button">🗑️ Hapus</button></div>';td.querySelector('.stock-edit').onclick=()=>open(x);td.querySelector('.stock-delete').onclick=()=>remove(x.id);tr.appendChild(td);});}
function start(){const box=$('stockHistory');if(!box)return;modal();const run=()=>setTimeout(()=>enhance().catch(e=>console.error('[STOK ACTIONS 53]',e)),200);new MutationObserver(run).observe(box,{childList:true,subtree:true});run();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('barokah:supabase-ready',()=>setTimeout(()=>enhance().catch(()=>{}),500));
})();